# Generated by Django 2.2.6 on 2019-10-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntry',
            new_name='JournalEntryModel',
        ),
    ]
